---
- hosts: localhost
  gather_facts: false

  tasks:

    - name: Provision instance
      ec2:
        instance_type: t2.micro
        key_name: tower2-demo-key
        count: "{{ instance_count }}"
        image: "{{ ami_id }}"
        region: us-east-1
        wait: true
      register: ec2

    - name: Add instance public IP to group
      add_host: hostname=ec2.instances.public_ip groups=ec2hosts
